environment:
  GITHUB_TOKEN:
    secure: {{ secrets.GIT_TOKEN }}
  NUGET_TOKEN:
    secure: {{ secrets.NUGET_API_KEY }}

# semantic-version requires node > 8.3 so instruct appveyor to install node 9
install:
  - ps: Install-Product node 9

# run out script
build_script:
  - ps: .\build.ps1

test: off

skip_tags: true

cache:
- tools -> build.cake
