name: Deploy to Nuget

on:
  push:
    branches: [ master ]
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  
jobs:
  build:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create NuGet Package
      run: dotnet pack -c Release --include-symbols
      working-directory: ./NivelCashback.Integration
    - name: Push package
      run: dotnet nuget push ./*.nupkg -k ${{ secrets.nuget_api_key }} -s 'https://api.nuget.org/v3/index.json' 
     
